# Site Settings
title: RabbitHole | A Nerd-Controlled Blog
email: hugo.b.brandao@gmail.com
description: The life and unlife of a nerd called Hugo
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
#google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: RabbitHole
user_description: Some text about me that I'm too lazy to write.
#disqus_username: disqus_username

# Social Media
# Remove the item if you don't need it
github_username: jhugobb
facebook_username: SizzleMeThis
#twitter_username: twitter_username
instagram_username: jotahbb
#linkedin_username: linkedin_username
#medium_username: medium_username

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Professional
    url: /pro/
  - title: Contact
    url: /contact/


# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
